### ISSUE TITLE
Handling postprocess.py post #275

### ISSUE THREAD

**Issue by salimfurth** [open-source-economics/OG-USA#279]
PR #275 moved `postprocess.py` to the directory `ogusa/scripts`. But the internal logic of `postprocess.create_diff` relies on it being run in the same directory in which `run_ogusa_serial.run_micro_macro` defines `BASELINE_DIR` and `REFORM_DIR`. 

`postprocess.create_diff` opens .pkl files from `./BASELINE_DIR` and `./REFORM_DIR`, and saves .csv files in its own default directory.

In the meantime, the script can be run in the iPython window on my system and it works. But this doesn't seem like the best permanent solution. Perhaps @PeterDSteinberg or @jdebacker have an elegant solution?

**Comment by jdebacker** [comment]
@salimfurth - in `ogusa/tests/ogusa_serial_test.py`, you need to replace the import of `postprocess` with

`from ogusa.scripts import postprocess`

**Comment by salimfurth** [comment]
@jdebacker - That's already in place. The issue isn't passing the Travis CI tests, it's running the actual script `postprocess.py`.

**Comment by jdebacker** [comment]
This issue has been fixed.

**Comment by salimfurth** [comment]
@jdebacker, how was this fixed?

**Comment by jdebacker** [comment]
@salimfurth I'm not having any issue running `run_ogusa_serial.py` and having the `postprocess` differences returned.  Are you still having issue running from OG-USA:master?

**Comment by salimfurth** [comment]
@jdebacker, I can't check now, because I'm running the full version of a branch. But last time I used master I had to jerry-rig a solution in order to run `postprocess`.

**Comment by salimfurth** [comment]
@jdebacker, re-checking this in `master`, I can confirm that postprocess still does not work in my normal workflow. Maybe I'm doing my workflow all wrong, but if so can someone post step by step instructions of what I ought to be doing?

**Comment by jdebacker** [comment]
@PeterDSteinberg Have you had any issue with this on OG-USA?

**Comment by PeterDSteinberg** [comment]
I did have an issue @jdebacker .  See #288 .  Please run locally and confirm it's okay.

**Comment by salimfurth** [comment]
@PeterDSteinberg & @jdebacker, my issue is much simpler, as noted in OP. With `postprocess` banished to the `scripts `directory, it does not recognize `ogusa` as a package and cannot open the directories it wants to open.
